### ISSUE TITLE
Team View Can be redesigned for better understanding of what every team member contributes most.

### ISSUE THREAD

**Issue by sks147** [counselling-cell-iitr/counselling-cell-iitr.github.io#8]
![image](https://user-images.githubusercontent.com/18536272/28761071-a5bbeacc-75c9-11e7-9aa3-85dddd10da02.png)

The circular picture looks amazing for a team profiles and teams should be categorised.
Just a suggestion.

**Comment by abhishek-jaisingh** [comment]
all suggestions are welcome! you can make a pr for that
